-- Bridge: CustomerProductBridge
-- Generated by DMJEDI (query-assist: view, not table)


CREATE OR REPLACE VIEW "bridge_CustomerProductBridge" AS
SELECT
    "Customer_hk"
    , "CustomerProduct_hk"
    , "Product_hk"
FROM "Customer"
JOIN "CustomerProduct"
    ON "CustomerProduct"."Customer_hk" = "Customer"."Customer_hk"
JOIN "Product"
    ON "CustomerProduct"."Product_hk" = "Product"."Product_hk"
;
