-- EffSat: RelationValidity (parent: CustomerProduct)
-- Generated by DMJEDI (effectivity satellite: MERGE/overwrite semantics)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
MERGE INTO "RelationValidity" AS target
USING "stg_RelationValidity" AS source
ON target."CustomerProduct_hk" = source."CustomerProduct_hk"
WHEN MATCHED THEN
    UPDATE SET
        "load_ts" = source."load_ts",
        "record_source" = source."record_source",
        "valid_from" = source."valid_from",
        "valid_to" = source."valid_to"
WHEN NOT MATCHED THEN
    INSERT ("CustomerProduct_hk", "load_ts", "record_source", "valid_from", "valid_to")
    VALUES (source."CustomerProduct_hk", source."load_ts", source."record_source", source."valid_from", source."valid_to");
