-- Staging view: CustomerMatch
-- Generated by DMJEDI (same-as link staging)


CREATE OR REPLACE VIEW "stg_CustomerMatch" AS
SELECT
    sha256(COALESCE(CAST("Customer_hk" AS VARCHAR), '') || '||' || COALESCE(CAST("Customer_hk" AS VARCHAR), '')) AS "CustomerMatch_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk",
    "Customer_hk",
    "confidence"
FROM "src_CustomerMatch";
