-- Staging view: CustomerProduct
-- Generated by DMJEDI


CREATE OR REPLACE VIEW "stg_CustomerProduct" AS
SELECT
    encode(sha256((COALESCE("Customer_hk", '') || '||' || COALESCE("Product_hk", ''))::bytea), 'hex') AS "CustomerProduct_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk",
    "Product_hk",
    "quantity"
FROM "src_CustomerProduct";
