-- SamLink: CustomerMatch
-- Generated by DMJEDI (same-as link: MERGE/overwrite semantics)


MERGE INTO "CustomerMatch" AS target
USING "stg_CustomerMatch" AS source
ON target."CustomerMatch_hk" = source."CustomerMatch_hk"
WHEN MATCHED THEN
    UPDATE SET
        "load_ts" = source."load_ts",
        "record_source" = source."record_source",
        "master_Customer_hk" = source."master_Customer_hk",
        "duplicate_Customer_hk" = source."duplicate_Customer_hk",
        "confidence" = source."confidence"
WHEN NOT MATCHED THEN
    INSERT ("CustomerMatch_hk", "load_ts", "record_source", "master_Customer_hk", "duplicate_Customer_hk", "confidence")
    VALUES (source."CustomerMatch_hk", source."load_ts", source."record_source", source."master_Customer_hk", source."duplicate_Customer_hk", source."confidence");
