-- Staging view: CustomerProduct
-- Generated by DMJEDI


CREATE OR REPLACE VIEW "stg_CustomerProduct" AS
SELECT
    sha256(COALESCE(CAST("Customer_hk" AS VARCHAR), '') || '||' || COALESCE(CAST("Product_hk" AS VARCHAR), '')) AS "CustomerProduct_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk",
    "Product_hk",
    "quantity"
FROM "src_CustomerProduct";
