-- NhSat: CurrentStatus (parent: Customer)
-- Generated by DMJEDI (non-historized: MERGE/overwrite semantics)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
MERGE INTO "CurrentStatus" AS target
USING "stg_CurrentStatus" AS source
ON target."Customer_hk" = source."Customer_hk"
WHEN MATCHED THEN
    UPDATE SET
        "load_ts" = source."load_ts",
        "record_source" = source."record_source",
        "status" = source."status",
        "updated_at" = source."updated_at"
WHEN NOT MATCHED THEN
    INSERT ("Customer_hk", "load_ts", "record_source", "status", "updated_at")
    VALUES (source."Customer_hk", source."load_ts", source."record_source", source."status", source."updated_at");
