-- Staging view: RelationValidity (parent: CustomerProduct)
-- Generated by DMJEDI (effectivity satellite staging)
CREATE OR REPLACE VIEW "stg_RelationValidity" AS
SELECT
    "CustomerProduct_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "valid_from",
    "valid_to"
FROM "src_RelationValidity";
