-- Staging view: CurrentStatus (parent: Customer)
-- Generated by DMJEDI (non-historized staging)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
CREATE OR REPLACE VIEW "stg_CurrentStatus" AS
SELECT
    "Customer_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "status",
    "updated_at"
FROM "src_CurrentStatus";
