-- Staging view: Customer
-- Generated by DMJEDI
CREATE OR REPLACE VIEW "stg_Customer" AS
SELECT
    sha256(COALESCE(CAST("customer_id" AS VARCHAR), '')) AS "Customer_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "customer_id"
FROM "src_Customer";
