-- NhLink: ActiveRelation
-- Generated by DMJEDI (non-historized: MERGE/overwrite semantics)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
MERGE INTO "ActiveRelation" AS target
USING "stg_ActiveRelation" AS source
ON target."ActiveRelation_hk" = source."ActiveRelation_hk"
WHEN MATCHED THEN
    UPDATE SET
        "load_ts" = source."load_ts",
        "record_source" = source."record_source",
        "Customer_hk" = source."Customer_hk",
        "Product_hk" = source."Product_hk",
        "score" = source."score"
WHEN NOT MATCHED THEN
    INSERT ("ActiveRelation_hk", "load_ts", "record_source", "Customer_hk", "Product_hk", "score")
    VALUES (source."ActiveRelation_hk", source."load_ts", source."record_source", source."Customer_hk", source."Product_hk", source."score");
