-- Hub: Customer
-- Generated by DMJEDI
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
CREATE TABLE IF NOT EXISTS "Customer" (
    "Customer_hk" CHAR(64) NOT NULL,
    "load_ts" TIMESTAMP NOT NULL,
    "record_source" VARCHAR(255) NOT NULL,
    "customer_id" INT
);
