-- Staging view: CustomerDetails (parent: Customer)
-- Generated by DMJEDI
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
CREATE OR REPLACE VIEW "stg_CustomerDetails" AS
SELECT
    "Customer_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    CURRENT_TIMESTAMP AS "load_end_ts",
    'dmjedi' AS "record_source",
    sha2(COALESCE("first_name", '') || '||' || COALESCE("last_name", '') || '||' || COALESCE("email", ''), 256) AS "hash_diff",
    "first_name",
    "last_name",
    "email"
FROM "src_CustomerDetails";
