-- Staging view: ActiveRelation
-- Generated by DMJEDI (non-historized staging)


CREATE OR REPLACE VIEW "stg_ActiveRelation" AS
SELECT
    encode(sha256((COALESCE("Customer_hk", '') || '||' || COALESCE("Product_hk", ''))::bytea), 'hex') AS "ActiveRelation_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk",
    "Product_hk",
    "score"
FROM "src_ActiveRelation";
