-- Staging view: CustomerMatch
-- Generated by DMJEDI (same-as link staging)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true


CREATE OR REPLACE VIEW "stg_CustomerMatch" AS
SELECT
    sha2(COALESCE("Customer_hk", '') || '||' || COALESCE("Customer_hk", ''), 256) AS "CustomerMatch_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk" AS "master_Customer_hk",
    "Customer_hk" AS "duplicate_Customer_hk",
    "confidence"
FROM "src_CustomerMatch";
