-- Hub: Customer
-- Generated by DMJEDI

CREATE TABLE IF NOT EXISTS Customer (
    Customer_hk BINARY NOT NULL,
    load_ts TIMESTAMP NOT NULL,
    record_source VARCHAR(255) NOT NULL,
    customer_id INT
);
