-- Staging view: Product
-- Generated by DMJEDI
CREATE OR REPLACE VIEW "stg_Product" AS
SELECT
    sha256(COALESCE(CAST("product_id" AS VARCHAR), '') || '||' || COALESCE(CAST("sku" AS VARCHAR), '')) AS "Product_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "product_id",
    "sku"
FROM "src_Product";
