-- EffSat: RelationValidity (parent: CustomerProduct)
-- Generated by DMJEDI (effectivity satellite: MERGE/overwrite semantics)
MERGE INTO "RelationValidity" AS target
USING "src_RelationValidity" AS source
ON target."CustomerProduct_hk" = source."CustomerProduct_hk"
WHEN MATCHED THEN
    UPDATE SET
        target."load_ts" = source."load_ts",
        target."record_source" = source."record_source",
        target."valid_from" = source."valid_from",
        target."valid_to" = source."valid_to"
WHEN NOT MATCHED THEN
    INSERT ("CustomerProduct_hk", "load_ts", "record_source", "valid_from", "valid_to")
    VALUES (source."CustomerProduct_hk", source."load_ts", source."record_source", source."valid_from", source."valid_to");
