-- Staging view: Customer
-- Generated by DMJEDI
CREATE OR REPLACE VIEW "stg_Customer" AS
SELECT
    encode(sha256((COALESCE("customer_id", ''))::bytea), 'hex') AS "Customer_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "customer_id"
FROM "src_Customer";
