-- SamLink: CustomerMatch
-- Generated by DMJEDI (same-as link: MERGE/overwrite semantics)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true
MERGE INTO "CustomerMatch" AS target
USING "src_CustomerMatch" AS source
ON target."CustomerMatch_hk" = source."CustomerMatch_hk"
WHEN MATCHED THEN
    UPDATE SET
        target."load_ts" = source."load_ts",
        target."record_source" = source."record_source",
        target."Customer_hk" = source."Customer_hk",
        target."Customer_hk" = source."Customer_hk",
        target."confidence" = source."confidence"
WHEN NOT MATCHED THEN
    INSERT ("CustomerMatch_hk", "load_ts", "record_source", "Customer_hk", "Customer_hk", "confidence")
    VALUES (source."CustomerMatch_hk", source."load_ts", source."record_source", source."Customer_hk", source."Customer_hk", source."confidence");
