-- Staging view: Product
-- Generated by DMJEDI
CREATE OR REPLACE VIEW "stg_Product" AS
SELECT
    encode(sha256((COALESCE("product_id", '') || '||' || COALESCE("sku", ''))::bytea), 'hex') AS "Product_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "product_id",
    "sku"
FROM "src_Product";
