-- Link: CustomerProduct
-- Generated by DMJEDI

CREATE TABLE IF NOT EXISTS CustomerProduct (
    CustomerProduct_hk BINARY NOT NULL,
    load_ts TIMESTAMP NOT NULL,
    record_source VARCHAR(255) NOT NULL,
    Customer_hk BINARY NOT NULL,
    Product_hk BINARY NOT NULL
);
