-- Staging view: CustomerProduct
-- Generated by DMJEDI
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true


CREATE OR REPLACE VIEW "stg_CustomerProduct" AS
SELECT
    sha2(COALESCE("Customer_hk", '') || '||' || COALESCE("Product_hk", ''), 256) AS "CustomerProduct_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk",
    "Product_hk",
    "quantity"
FROM "src_CustomerProduct";
