-- Staging view: ActiveRelation
-- Generated by DMJEDI (non-historized staging)
-- NOTE: Requires ANSI_MODE=true and spark.sql.doubleQuotedIdentifiers=true


CREATE OR REPLACE VIEW "stg_ActiveRelation" AS
SELECT
    sha2(COALESCE("Customer_hk", '') || '||' || COALESCE("Product_hk", ''), 256) AS "ActiveRelation_hk",
    CURRENT_TIMESTAMP AS "load_ts",
    'dmjedi' AS "record_source",
    "Customer_hk",
    "Product_hk",
    "score"
FROM "src_ActiveRelation";
