-- PIT: CustomerPit (anchor: Customer)
-- Generated by DMJEDI (query-assist: view, not table)
CREATE OR REPLACE VIEW "pit_CustomerPit" AS
SELECT
    "h"."Customer_hk"
    , "h"."load_ts" AS "snap_load_ts"
    , "CustomerDetails_alias"."load_ts" AS "CustomerDetails_load_ts"
    , "CustomerDetails_alias"."hash_diff" AS "CustomerDetails_hash_diff"
FROM "Customer" "h"
LEFT JOIN "CustomerDetails" AS "CustomerDetails_alias"
    ON "CustomerDetails_alias"."Customer_hk" = "h"."Customer_hk"
    AND "CustomerDetails_alias"."load_ts" = (
        SELECT MAX("s2"."load_ts") FROM "CustomerDetails" "s2"
        WHERE "s2"."Customer_hk" = "h"."Customer_hk"
    )
;
